# Generated by Django 5.2.7 on 2025-11-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_created_at_product_description_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
