# Generated by Django 5.2.7 on 2025-11-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_product_image_alter_product_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderTrack',
        ),
    ]
