# Generated by Django 5.2.7 on 2025-11-05 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_userlogin_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='can_access_admin',
            field=models.BooleanField(default=False),
        ),
    ]
